### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by JustinLung** [WesleySchorel/the-startup-responsive-interactieve-website#8]
Maak gebruik van CSS variables:

```css
:root {
 --color-grey: #333;
}
```
https://github.com/WesleySchorel/the-startup-responsive-interactieve-website/blob/536b39b0f9dea57da97ada3fc28dd4029fa1fcc1/styles/style.css#L11
